sudo: required
services: 
  - docker
before_install: 
  #travis encryption afterward instruction
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  #download google sdk and install it locally in travis ci
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  #setup kubectl in travis ci environment
  - gcloud components update kubectl
  #authentication with google cloud service account (same as AWS IAM)
  - gcloud auth activate-service-account --key-file service-account.json


