apiVersion: skaffold/v1beta2 #inject source code only works for project has ability to detect changes and do auto reload
kind: Config
build: 
  local:
    push: false
  artifacts:
    - image: qianweng/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync: #inject the source code into the source code pot instead of rebuild image
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: qianweng/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync: #inject the source code into the source code pot instead of rebuild image
        '**/*.js': .  
    - image: qianweng/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync: #inject the source code into the source code pot instead of rebuild image
        '**/*.js': .         
deploy:
  kubectl:
      manifests: #will automatically delete all those pod on close. dont delete persistent pod such as database if you want to keep it around
        - k8s/client-deployment.yaml
        - k8s/server-deployment.yaml
        - k8s/worker-deployment.yaml
        - k8s/server-cluster-ip-service.yaml
        - k8s/client-cluster-ip-service.yaml