#tell cert manager to where it should go to get certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory #the link to the vert manager
    email: 'qweng1577@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}